import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';

export default function LoadingCardHeader() {
  return (
    <div
      className={`
        flex
        w-full
        flex-col
        items-center
        gap-2
        bg-velblue
        p-4
      `}
    >
      <div
        className={`
          flex
          w-full
          items-center
          bg-velblue
        `}
      >
        <div
          className={`
            flex
            w-1/2
            justify-start
          `}
        >
          <Badge
            variant={`outline`}
            className={`
            text-white
            `}
          >
            Loading...
          </Badge>
        </div>
        <div
          className={`
            shrink-0
          `}
        >
          <h2
            className={`
              text-center
              text-xl
              font-bold
              text-white
            `}
          >
            Loading...
          </h2>
        </div>
        <div
          className={`
            flex
            w-1/2
            justify-end
          `}
        ></div>
      </div>
      <div
        className={`
          flex
          flex-row
          items-center
          justify-evenly
          gap-2
        `}
      >
        <p
          className={`
            text-center
            text-xs
            text-slate-200
            `}
        >
          Created:&nbsp;Loading...
        </p>
        <Separator orientation={`vertical`} className="h-4" />
        <p
          className={`
            text-center
            text-xs
            text-slate-200
          `}
        >
          Updated:&nbsp;Loading...
        </p>
      </div>
    </div>
  );
}
